logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: DEBUG
management:
  security:
    enabled: false
spring:
  devtools:
    restart:
      exclude: static/**